### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by JeremyRaven** [mkagenius/osm2maya#3]
# Error: TypeError: file <maya console> line 69: list indices must be integers or slices, not float #

I tried typecasting to int for lines 69 and 70 but it doesnt recognise it for some reason, Maya 2022

**Comment by mkagenius** [comment]
Weird that it was working all this while even after this bug (maybe something changed in the 2022 Maya).
I don't have access to a laptop at this moment, can you try double slash instead of single in those two lines, like

float(all_buildings[sz//2][0][0][0])

Typecasting should have worked too: float(all_buildings[int(sz/2)][0][0][0])

**Comment by JeremyRaven** [comment]
My mistake I was typecasting the whole line of code as follows: int(all_buildings[sz/)][0][0][0]) (incorrect)

But your code works: float(all_buildings[int(sz/2)][0][0][0])

Thanks.
